// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The Prisma CLI (db push / migrate) hangs against Supabase's pooled
    // connection (pgbouncer transaction mode doesn't support what the CLI
    // needs). Route CLI operations through the direct connection instead.
    // This only affects `prisma.config.ts` (CLI); the running app connects
    // via DATABASE_URL (pooled) directly in src/index.ts.
    url: process.env["DIRECT_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
